### ISSUE TITLE
Trip creation component

### ISSUE THREAD

**Issue by nicoga-code** [easy-wheels/easy-wheels-front-end#34]
### TODO:
As a dev i want to create a component inside the main map to create a new trip

### CheckList
* [x]  It will be able to select role(driver, passanger)
* [ ]  It will be able to select number of passangers if the user is a driver
* [x]  It will be able to select the date of the trip
