### ISSUE TITLE
As a dev i create the coin purse view

### ISSUE THREAD

**Issue by rodavid404** [easy-wheels/easy-wheels-front-end#4]
### TODO:
Make the cion purse view

### CheckList
* [ ]  Make the Coin purse view
* [ ]  Make the add money view
* [ ]  Make the add payment method
* [ ]  Make the transaccion history
